name: per_fin_man
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>=0.12.0 <0.13.0'
transformers:
- polymer:
    entry_points: web/per_fin_man.html
